### PR TITLE
Switch to gnutls

### PR DESCRIPTION
**Pull request by Azd325**
Thanks to @thenexxuz

### CODE REVIEW

**Comment by KillWolfVlad** [comment]
Why you don't want rebuild `nodegit` with system `libcurl`? It is legal, stable and durable solution.

**Comment by MarcinWieczorek** [comment]
Why don't we?

**Comment by KillWolfVlad** [comment]
Really? You are agree? I will send PR soon.

**Comment by MarcinWieczorek** [comment]
Well convince me, if that doesn't involve a crack then why not? I hope it's not against some EULA too. I guess it is done in a similar way as your crack, right?

**Comment by KillWolfVlad** [comment]
Source code (from app.asar) will not be changed. GitKraken will be launched on new electron from github and all native modules will be rebuilded and linked with system libs. No cracks.

**Comment by KillWolfVlad** [comment]
Electron from github releases. System electron can be different in arch repo and manjaro. And gitkraken can not work with system electron.

**Comment by MarcinWieczorek** [comment]
Can't we somehow recompile it for system electron?

**Comment by KillWolfVlad** [comment]
Yes, we can. I will do it.

**Comment by Azd325** [comment]
Can you provide me somewhere a official  docs about this recompiling.

**Comment by KillWolfVlad** [comment]
> Can you provide me somewhere a official docs about this recompiling.

No docs.

**Pull request merged**
