### PR TITLE
Merging branch to remove unused deps

### PR DESCRIPTION
**Pull request by thenexxuz**

### CODE REVIEW

**Comment by MarcinWieczorek** [comment]
Changing the `pkgrel` will force users to rebuild the package. I don't think that it's needed, the deps would just be removed in next version update.

**Comment by thenexxuz** [comment]
I changed the `pkgrel` back to 2

**Comment by Azd325** [comment]
@thenexxuz @MarcinWieczorek Thanks guys to keeping track. :)
@thenexxuz Did you push? I don't want to take the complete  credit for the change. Don't see the pkrel change.

**Comment by Azd325** [comment]
Ahh I see. You reverted the change. :D 
Merged in https://github.com/Azd325/gitkraken/commit/7c32e73b64c5717fd372f688b9b41aeb73771975

**Comment by Azd325** [comment]
@MarcinWieczorek @thenexxuz Can i one of you verify if we need this change too.
https://aur.archlinux.org/cgit/aur.git/commit/?h=gitkraken-standalone&id=6edcbed007f73ccca8c88c235197fe26cd8e2faf

**Comment by jtaala** [comment]
> @MarcinWieczorek @thenexxuz Can i one of you verify if we need this change too.
> https://aur.archlinux.org/cgit/aur.git/commit/?h=gitkraken-standalone&id=6edcbed007f73ccca8c88c235197fe26cd8e2faf

Hey Azd325, maintainer of gitkraken-standalone here, just checked and desktop-file-utils is not explicitly needed (in a previous clean chroot build saw it was used but guess not explicitly needed as a dep).  I'll remove it as dep soon.

Cheers, Jay.

**Comment by Azd325** [comment]
@jtaala Thanks for the info.

**Pull request closed without merging**
