### PR TITLE
Bump version to 1.8.1

### PR DESCRIPTION
**Pull request by juanpedrob9**

### CODE REVIEW

**Comment by MarcinWieczorek** [comment]
I confirm the checksum
`79f0c065dfc11d25e417e8d85a4a2edf  v1.8.1.tar.gz`

**Comment by Azd325** [comment]
Thanks guys.

**Comment by juanpedrob9** [comment]
You're welcome.

BTW my name's Jean-Pier and I live in Canada. Hi! :) 

I was wondering, how would you prefer to procede for next updates?

**Comment by MarcinWieczorek** [comment]
That guy should be added to contributors

**Comment by Azd325** [comment]
@MarcinWieczorek He is already invited to be a contributor ;)

@juanpedrob9 ntmu jean-pier. I'm Tim
Currently, the state is that I activated that only reviewed PR can get merged.
https://help.github.com/articles/enabling-required-reviews-for-pull-requests/
I'm not sure what happens if @MarcinWieczorek reviews the change if this counts too that you'll be able to merge it because we can not push forced history changes to AUR.
If this done I push the changes to the AUR.

**Comment by juanpedrob9** [comment]
Hi Tim,
Yeah i figured out I could'nt push to master.. that's kinda why i created the branch.. Would you prefer a PR from my repo/fork or like did this time from a new vX.Y.Z branch? Either way I really don't mind, just wanna make sure it's ok with you.

**Comment by MarcinWieczorek** [comment]
I mean't the PKGBUILD

**Comment by Azd325** [comment]
@juanpedrob9 I don't mind. :)
@MarcinWieczorek Ahh, I see. He can add himself if he like.

**Pull request merged**
