### PR TITLE
Bump to v7.6.0

### PR DESCRIPTION
**Pull request by thenexxuz**

### CODE REVIEW

**Comment by thenexxuz** [comment]
What needs to happen to get the linting correct?

**Comment by GeoZac** [comment]
Related ? https://github.com/github/super-linter/issues/409

**Comment by wpenton-itc** [comment]
Well v7.6.1 is out now too...

**Comment by Azd325** [comment]
Thanks I didn't got an email about these PRs....
7.6.1 is now out.
Merged in https://github.com/Azd325/gitkraken/commit/a23a13d2272f7893b27252e4d96c297a380a8a05

**Pull request closed without merging**
