### PR TITLE
Update PKGBUILD

### PR DESCRIPTION
**Pull request by darkchix**
Updated to version 2.2.1, updated md5 checksum hash and added libxss dependency

### CODE REVIEW

**Comment by Azd325** [comment]
Can you update the .SRCINFO too.
How it comes that libxss is now needed?

**Comment by vhbsouza** [comment]
@Azd325 This PR is outdated, shouldn't it be deleted?

**Comment by MarcinWieczorek** [comment]
Yeah it should, but @darkchix has never replied why should libxss be added as a dependency.

**Comment by darkchix** [comment]
Well I am using Gnome 3 desktop environment and after one install Gitkraken
won't start and displayed errors of lacking libxss library. But maybe it
was just one time case.

On Apr 7, 2017 2:39 PM, "Marcin Wieczorek" <notifications@github.com> wrote:

Yeah it should, but @darkchix <https://github.com/darkchix> has never
replied why should libxss be added as a dependency.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Azd325/gitkraken/pull/28#issuecomment-292525474>, or mute
the thread

**Comment by MarcinWieczorek** [comment]
Well please confirm the issue and open a new pull request (if it's valid) commiting only the dependency change. This PR is outdated anyway.

**Comment by Azd325** [comment]
@darkchix libxss is now included https://github.com/Azd325/gitkraken/commit/041f41de36baa229317cd45b95f79e2acb6247a9

**Comment by darkchix** [comment]
Thanks

**Pull request closed without merging**
