### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by MarcinWieczorek**
Why can't I push directly without a review? :(

### CODE REVIEW

**Comment by Azd325** [comment]
Because I enabled an option that every PR needs a review.
pro tip: I think you can do a review on your own, too.

**Comment by MarcinWieczorek** [comment]
I can't ;)

**Comment by MarcinWieczorek** [comment]
I tried to push from the shell, I don't know how am I supposed to get a review without a PR

**Comment by Azd325** [comment]
Because this branch is protected by changes. You have to create a branch before there can be something merged.

screen shot 2017-04-07 at 15 02 17

**Comment by MarcinWieczorek** [comment]
Just what I did

**Pull request merged**
