### PR TITLE
add travis

### PR DESCRIPTION
**Pull request by casz**
Build took 4 minutes and validates gitkraken
https://travis-ci.org/casz/gitkraken/builds/512334381

### CODE REVIEW

**Comment by Azd325** [comment]
Cool merged in https://github.com/Azd325/gitkraken/commit/ce928bf8e33cad1ce6f05fb259dabad5124760ed

**Comment by MarcinWieczorek** [comment]
Great, can you make it run namcap too?

**Comment by casz** [comment]
@MarcinWieczorek feel free to send a PR? 😅

**Comment by MarcinWieczorek** [comment]
I don't have time spare. I guess that's only about adding a line after makepkg?

**Comment by casz** [comment]
On GitHub edit file, fire and forget 😄 hope it works! 😆

**Pull request closed without merging**
