### PR TITLE
org.freedesktop.secrets instead of gnome-keyring

### PR DESCRIPTION
**Pull request by GottZ**
see https://www.archlinux.org/todo/gnome-keyring-dependency-replacement-with-orgfreedesktopsecrets/

packages providing libsecret: gnome-keyring and keepassxc

thus replacing gnome-keyring with org.freedesktop.secrets allows choosing between either of them.

### CODE REVIEW

**Comment by MarcinWieczorek** [comment]
Looks legit. Have you actually tested the solution for both frontends?

**Comment by GottZ** [comment]
i'm actually using gitkraken successfully with keepassxc right now.
signed in to github, my own gitlab installation, bitbucket and more.
everything works as expected so far.

**Comment by Azd325** [comment]
@GottZ Sound great. Can you follow these [steps](https://github.com/Azd325/gitkraken#update-package) to get the PR ready to merge?

**Comment by Azd325** [comment]
Superseded in https://github.com/Azd325/gitkraken/pull/144

**Pull request closed without merging**
