### PR TITLE
Bump to v3.4.0-2 (libpsl rebuild)

### PR DESCRIPTION
**Pull request by DerTieran**
[`libpsl`](https://www.archlinux.org/packages/core/x86_64/libpsl/) version changed (0.19.1-1 -> 0.20.0-1) which required a rebuild for me.

### CODE REVIEW

**Comment by DerTieran** [comment]
Okay, I couldn't start gitkraken after updating my other packages
```sh
/opt/gitkraken/gitkraken: error while loading shared libraries: libpsl.so.5: cannot open shared object file: No such file or directory
```
I tried reinstalling and even completely removing and installing again.
Both did not work so I cloned this repo and "rebuild" it (`makepkg -si`), this allowed me to start it again.
I'm not an expert with arch packages but I saw that other packages like [`wget`](https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/wget) did the same so I figured it might be needed.

My bad, feel free to close this then :smile:

**Comment by KillWolfVlad** [comment]
GitKraken require [libcurl-gnutls](https://www.archlinux.org/packages/community/x86_64/libcurl-gnutls/)
[libcurl-gnutls](https://www.archlinux.org/packages/community/x86_64/libcurl-gnutls/) require [libpsl](https://www.archlinux.org/packages/core/x86_64/libpsl/)

How you should update your system:
libpsl 0.19.1-1 -> 0.20.0-1
libcurl-gnutls 7.58.0-1 -> 7.58.0-2
GitKraken not changes

**Comment by DerTieran** [comment]
Hmm okay, both dependencys got updated, but then I will close this PR.

**Comment by MarcinWieczorek** [comment]
You're supposed to handle library updates on your own. It works for official repos, but not for AUR. Thanks for noticing though.

**Pull request closed without merging**
