### PR TITLE
Update PKGBUILD

### PR DESCRIPTION
**Pull request by YogliB**
Update the download URL.

### CODE REVIEW

**Comment by MarcinWieczorek** [comment]
Doesn't the current url work?

**Comment by Azd325** [comment]
We use this URL, so we are independent of version changes.

**Comment by MarcinWieczorek** [comment]
I wanted to give him a chance to explain :(

**Comment by Azd325** [comment]
He can still explain himself and if it is a good reason he can reopen this PR. ;)

**Comment by YogliB** [comment]
I thought the URL was broken since YAY didn't manage to install the package for a few times of me trying (internet was fine), but suddenly it started working (file is being loaded just fine).

Sorry for the hassle :)

**Comment by MarcinWieczorek** [comment]
Cool, thanks for reaching out anyway.

**Pull request closed without merging**
